@startuml
class SampleRenderer {
    - cudaContext: CUcontext
    - stream: CUstream
    - optixContext: OptixDeviceContext
    - pipeline: OptixPipeline
    - optix_module: OptixModule
    - raygenPGs: vector<OptixProgramGroup>
    - missPGs: vector<OptixProgramGroup>
    - hitgroupPGs: vector<OptixProgramGroup>
    - sbt: OptixShaderBindingTable
    - launchParams: LaunchParams
    - launchParamsBuffer: CUDABuffer
    - colorBuffer: CUDABuffer
    - model: IcosahedronTriangleMesh
    - vertexBuffer: CUDABuffer
    - indexBuffer: CUDABuffer
    - asBuffer: CUDABuffer
    + SampleRenderer(model: IcosahedronTriangleMesh)
    + render()
    + resize(newSize: vec2i)
    + downloadPixels(h_pixels: uint32_t[])
    + setCamera(camera: Camera)
    - initOptix()
    - createContext()
    - createModule()
    - createRaygenPrograms()
    - createMissPrograms()
    - createHitgroupPrograms()
    - createPipeline()
    - buildSBT()
    - buildAccel(): OptixTraversableHandle
}

class IcosahedronTriangleMesh {
    + vertex: vector<vec3f>
    + index: vector<vec3i>
    + color: vec3f
    + addUnitIcosahedron(xfm: affine3f)
    + addIcosahedron(center: vec3f, size: vec3f)
}

class Camera {
    + from: vec3f
    + at: vec3f
    + up: vec3f
}

class SampleWindow {
    - sample: SampleRenderer
    + SampleWindow(title, model, camera, worldScale)
    + render(): void
    + draw(): void
    + resize(newSize: vec2i): void
}

class GLFCameraWindow {
    # cameraFrame: CameraFrame
    + GLFCameraWindow(title, from, at, up, worldScale)
}

SampleWindow --|> GLFCameraWindow
SampleWindow *-- SampleRenderer
SampleRenderer *-- IcosahedronTriangleMesh
SampleRenderer --> Camera

@enduml
