@startuml
package "geo-sub-optix" {
    
    package "geo-sub" #LightBlue {
        [main.cpp]
        [SampleRenderer]
        [IcosahedronTriangleMesh]
        [Subdividers]
        [devicePrograms.cu]
    }
    
    package "glfWindow" #LightGreen {
        [GLFWindow]
        [GLFCameraWindow]
    }
    
    package "gdt" #LightYellow {
        [vec3f / vec3i]
        [affine3f]
    }
    
    package "glfw-3.3.9" #LightCoral {
        [GLFW Library]
    }
}

package "External SDKs" {
    [OptiX 9.0] #Orange
    [CUDA 13.0] #Orange
    [OpenGL] #Orange
}

[SampleRenderer] --> [devicePrograms.cu]
[SampleRenderer] --> [OptiX 9.0]
[Subdividers] --> [vec3f / vec3i]
[GLFWindow] --> [GLFW Library]
[GLFWindow] --> [OpenGL]

@enduml
